### ISSUE TITLE
Error: Not freed memory blocks: 1, total unfreed memory 0.000244 MB

### ISSUE THREAD

**Issue by MotiBaadror** [minar09/pix2surf_windows#1]
I am getting below error when I am running the code in colab. 
Error: Not freed memory blocks: 1, total unfreed memory 0.000244 MB

**Comment by minar09** [comment]
I am sorry, I am a total amateur when it comes to colab. I hope you can find some good solutions. You may also refer to the original pix2surf repository.

**Comment by MotiBaadror** [comment]
@minar09  Thank you

**Comment by juanmarin96** [comment]
Same error here, @MotiBaadror could you resolve this?

**Comment by wukong-me** [comment]
@MotiBaadror @juanmarin96 Same error here,could you resolve this?
